import { useEffect, useRef, useState, type ReactNode } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AppHeader } from "../components/CatalogUi";
import { useC5 } from "../api/C5ApiContext";
import type { CreatedReportShare, InAppNotification, NotificationPage, PrivacySettings, PublicFilmPage, PublicPopcornPage, ReportExport, ResourcePrivacy, SharedTasteReport, TasteReport, TasteReportSummaryPage } from "../api/c5";
import styles from "../styles/c5.module.css";
import { localFeaturesEnabled } from "../config/localFeatures";

function Layout({ title, lead, children, localOnly = false }: { title: string; lead?: string; children: ReactNode; localOnly?: boolean }) { return <main className={styles.page}><div className={styles.inner}><AppHeader compact /><header className={styles.hero}><p className={styles.eyebrow}>{localOnly ? "LOCAL MVP" : "MY FEELM"}</p><h1>{title}</h1>{lead && <p>{lead}</p>}</header>{children}</div></main>; }
function ErrorBox({ error }: { error: unknown }) { return error ? <p className={styles.error} role="alert">{error instanceof Error ? error.message : "요청을 처리하지 못했어요."}</p> : null; }
function More({ enabled, onClick }: { enabled: boolean; onClick: () => void }) { return enabled ? <button className={styles.more} onClick={onClick}>다음 페이지</button> : null; }
function periodLabel(start: string, end: string) { return `${start} ~ ${end}`; }

export function ReportsPage() {
  const { api } = useC5(); const navigate = useNavigate();
  const [page, setPage] = useState<TasteReportSummaryPage | null>(null); const [error, setError] = useState<unknown>(); const [periodStart, setPeriodStart] = useState("");
  async function load(cursor?: string) { try { const next = await api.listReports(cursor); setPage((current) => cursor && current ? { ...next, items: [...current.items, ...next.items] } : next); } catch (reason) { setError(reason); } }
  useEffect(() => { void load(); }, [api]);
  async function create() { try { const report = await api.createReport(periodStart); navigate(`/me/reports/${report.reportId}`); } catch (reason) { setError(reason); } }
  return <Layout title="반기 리포트" lead="감상 수·평가 수·평균과 실제 감상 영화만 담는 사실 리포트입니다."><section className={styles.toolbar}><label>반기 시작일<input type="date" value={periodStart} onChange={(event) => setPeriodStart(event.target.value)} /></label><button className={styles.primary} disabled={!periodStart} onClick={create}>새 revision 만들기</button></section><ErrorBox error={error} />{!page ? <p role="status">리포트를 불러오는 중…</p> : page.items.length === 0 ? <p className={styles.empty}>아직 만든 리포트가 없어요.</p> : <div className={styles.cards}>{page.items.map((item) => <article key={item.reportId}><p>{item.status}</p><h2>{periodLabel(item.periodStart, item.periodEnd)}</h2><p>revision {item.revision}</p><Link to={`/me/reports/${item.reportId}`}>전체 보기</Link></article>)}</div>}<More enabled={Boolean(page?.hasNext && page.nextCursor)} onClick={() => void load(page?.nextCursor ?? undefined)} /></Layout>;
}
export function ReportDetailPage() {
  const { reportId = "" } = useParams(); const { api } = useC5();
  const [report, setReport] = useState<TasteReport | null>(null); const [error, setError] = useState<unknown>();
  async function load(cursor?: string) { try { const next = await api.getReport(reportId, cursor); setReport((current) => cursor && current ? { ...next, periodItems: { ...next.periodItems, items: [...current.periodItems.items, ...next.periodItems.items] } } : next); } catch (reason) { setError(reason); } }
  useEffect(() => { void load(); }, [api, reportId]);
  return <Layout title="리포트 상세" lead="이 revision에 고정된 실제 영화 전체를 페이지 끝까지 확인할 수 있어요."><ErrorBox error={error} />{!report ? <p role="status">상세를 불러오는 중…</p> : <><dl className={styles.metrics}><div><dt>감상</dt><dd>{report.metrics.viewingCount}</dd></div><div><dt>평가</dt><dd>{report.metrics.ratedCount}</dd></div><div><dt>평균</dt><dd>{report.metrics.averageRating ?? "없음"}</dd></div></dl><div className={styles.actions}>{localFeaturesEnabled && <><Link className={styles.primaryLink} to={`/me/reports/${reportId}/export`}>PDF 내보내기</Link><Link className={styles.secondaryLink} to={`/me/reports/${reportId}/share`}>공유</Link></>}</div>{report.periodItems.items.length === 0 ? <p className={styles.empty}>이 기간의 활동이 없어요.</p> : <ul className={styles.rows}>{report.periodItems.items.map((item) => <li key={`${item.movieId}-${item.watchedAt}`}><strong>{item.displayTitle}</strong><span>{item.watchedAt.slice(0, 10)} · {item.rating ? `${item.rating}/5` : "평가 없음"}</span></li>)}</ul>}<More enabled={report.periodItems.hasNext && Boolean(report.periodItems.nextCursor)} onClick={() => void load(report.periodItems.nextCursor ?? undefined)} /></>}</Layout>;
}

export function ReportExportPage() {
  const { reportId = "" } = useParams(); const { api } = useC5(); const [job, setJob] = useState<ReportExport | null>(null); const [error, setError] = useState<unknown>();
  async function create() { try { setJob(await api.createExport(reportId)); } catch (reason) { setError(reason); } }
  async function refresh() { if (!job) return; try { setJob(await api.getExport(job.exportId)); } catch (reason) { setError(reason); } }
  async function download() { if (!job) return; try { const blob = await api.downloadExport(job.exportId); const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = `feelm-report-${reportId}.pdf`; anchor.click(); URL.revokeObjectURL(href); } catch (reason) { setError(reason); } }
  return <Layout title="PDF 내보내기" lead="loopback local worker가 만드는 임시 PDF이며 최대 24시간 보관됩니다." localOnly><ErrorBox error={error} />{!job ? <button className={styles.primary} onClick={create}>PDF 작업 만들기</button> : <section className={styles.status} aria-live="polite"><h2>{job.status}</h2><p>만료 {job.expiresAt}</p><div className={styles.actions}>{job.status === "READY" ? <button className={styles.primary} onClick={download}>다운로드</button> : <button className={styles.secondary} onClick={refresh}>상태 새로고침</button>}</div></section>}</Layout>;
}

const resources = ["PROFILE", "FILM", "POPCORN"] as const;
export function PrivacyPage() {
  const { api } = useC5(); const [settings, setSettings] = useState<PrivacySettings | null>(null); const [draft, setDraft] = useState<ResourcePrivacy[]>([]); const [error, setError] = useState<unknown>();
  useEffect(() => { void api.getPrivacy().then((value) => { setSettings(value); setDraft(value.resources); }).catch(setError); }, [api]);
  function change(resource: ResourcePrivacy["resource"], visibility: ResourcePrivacy["visibility"]) { setDraft(resources.map((name) => ({ resource: name, visibility: name === resource ? visibility : draft.find((item) => item.resource === name)?.visibility ?? "PRIVATE" }))); }
  async function save() { if (!settings) return; try { const value = await api.replacePrivacy(draft, settings.revision); setSettings(value); setDraft(value.resources); } catch (reason) { setError(reason); } }
  return <Layout title="공개 범위" lead="세 항목은 서로 독립이며 기본값은 모두 비공개입니다."><ErrorBox error={error} />{!settings ? <p role="status">설정을 불러오는 중…</p> : <><div className={styles.settings}>{resources.map((resource) => <label key={resource}><span><strong>{resource}</strong><small>{resource === "PROFILE" ? "닉네임" : resource === "FILM" ? "활성 Film 전체" : "활성 Popcorn 전체"}가 공개됩니다.</small></span><select value={draft.find((item) => item.resource === resource)?.visibility ?? "PRIVATE"} onChange={(event) => change(resource, event.target.value as "PRIVATE" | "PUBLIC")}><option value="PRIVATE">비공개</option><option value="PUBLIC">공개</option></select></label>)}</div><div className={styles.actions}><button className={styles.primary} onClick={save}>전체 설정 저장</button>{settings.resources.some((item) => item.resource === "PROFILE" && item.visibility === "PUBLIC") && <Link className={styles.secondaryLink} to={`/people/${settings.publicProfileId}`}>공개 프로필 확인</Link>}</div><p className={styles.notice}>공개로 바꾸면 publicProfileId를 아는 사람이 허용한 리소스를 볼 수 있습니다.</p></>}</Layout>;
}

export function PublicProfilePage() {
  const { publicProfileId = "" } = useParams(); const { api } = useC5();
  const [nickname, setNickname] = useState(""); const [film, setFilm] = useState<PublicFilmPage | null>(null); const [popcorns, setPopcorns] = useState<PublicPopcornPage | null>(null); const [error, setError] = useState<unknown>();
  async function loadFilm(cursor?: string) { try { const next = await api.listPublicFilm(publicProfileId, cursor); setFilm((current) => cursor && current ? { ...next, items: [...current.items, ...next.items] } : next); } catch (reason) { setError(reason); } }
  async function loadPopcorns(cursor?: string) { try { const next = await api.listPublicPopcorns(publicProfileId, cursor); setPopcorns((current) => cursor && current ? { ...next, items: [...current.items, ...next.items] } : next); } catch (reason) { setError(reason); } }
  useEffect(() => { void Promise.all([api.getPublicProfile(publicProfileId), loadFilm(), loadPopcorns()]).then(([profile]) => setNickname(profile.nickname)).catch(setError); }, [api, publicProfileId]);
  return <Layout title={nickname || "공개 프로필"} lead="사용자가 명시적으로 공개한 리소스만 표시합니다."><ErrorBox error={error} /><section><h2>Film 전체</h2>{film?.items.length === 0 ? <p className={styles.empty}>공개 Film이 없어요.</p> : <ul className={styles.rows}>{film?.items.map((item) => <li key={item.frameId}><strong>{item.displayTitle}</strong><span>{item.watchedAt.slice(0, 10)}</span></li>)}</ul>}<More enabled={Boolean(film?.hasNext && film.nextCursor)} onClick={() => void loadFilm(film?.nextCursor ?? undefined)} /></section><section><h2>Popcorn 전체</h2>{popcorns?.items.length === 0 ? <p className={styles.empty}>공개 Popcorn이 없어요.</p> : <ul className={styles.rows}>{popcorns?.items.map((item) => <li key={item.popcornId}><strong>{item.displayTitle}</strong></li>)}</ul>}<More enabled={Boolean(popcorns?.hasNext && popcorns.nextCursor)} onClick={() => void loadPopcorns(popcorns?.nextCursor ?? undefined)} /></section></Layout>;
}

export function ReportSharePage() {
  const { reportId = "" } = useParams(); const { api } = useC5(); const [share, setShare] = useState<CreatedReportShare | null>(null); const [revoked, setRevoked] = useState(false); const [error, setError] = useState<unknown>();
  async function create() { try { setShare(await api.createShare(reportId)); } catch (reason) { setError(reason); } }
  async function copy() { if (!share) return; await navigator.clipboard.writeText(share.shareHref.includes("#") ? share.shareHref : `${window.location.origin}/shared-report#token=${share.rawToken}`); }
  async function revoke() { if (!share) return; try { await api.revokeShare(share.shareId); setRevoked(true); setShare(null); } catch (reason) { setError(reason); } }
  return <Layout title="리포트 공유" lead="raw token은 생성 직후 이 화면에서 한 번만 확인할 수 있고 서버에는 hash만 남습니다." localOnly><ErrorBox error={error} />{revoked && <p className={styles.notice} role="status">공유와 viewer session을 취소했습니다.</p>}{!share ? <button className={styles.primary} onClick={create}>공유 링크 한 번 생성</button> : <section className={styles.status}><p>만료 {share.expiresAt}</p><p className={styles.secretOnce}>링크를 복사한 뒤 이 값을 다시 조회할 수 없습니다.</p><div className={styles.actions}><button className={styles.primary} onClick={copy}>링크 복사</button><button className={styles.danger} onClick={revoke}>즉시 취소</button></div></section>}</Layout>;
}

export function SharedReportPage() {
  const { api, viewerSession, setViewerSession } = useC5(); const [report, setReport] = useState<SharedTasteReport | null>(null); const [error, setError] = useState<unknown>();
  const rawToken = useRef((() => { const fragment = new URLSearchParams(window.location.hash.replace(/^#/, "")); const value = fragment.get("token") ?? fragment.get("rawToken") ?? ""; if (window.location.hash) window.history.replaceState(window.history.state, "", `${window.location.pathname}${window.location.search}`); return value; })());
  async function load(cursor?: string, explicitToken?: string) { const token = explicitToken ?? viewerSession?.viewerSessionToken; if (!token) { setError(new Error("유효한 공유 링크가 필요해요.")); return; } try { const next = await api.getSharedReport(token, cursor); setReport((current) => cursor && current ? { ...next, report: { ...next.report, periodItems: { ...next.report.periodItems, items: [...current.report.periodItems.items, ...next.report.periodItems.items] } } } : next); } catch (reason) { setError(reason); } }
  useEffect(() => { let active = true; void (async () => { try { let token = viewerSession?.viewerSessionToken; if (!token && rawToken.current) { const session = await api.exchangeShare(rawToken.current); rawToken.current = ""; if (!active) return; setViewerSession(session); token = session.viewerSessionToken; } if (token) await load(undefined, token); else setError(new Error("유효한 공유 링크가 필요해요.")); } catch (reason) { rawToken.current = ""; if (active) setError(reason); } })(); return () => { active = false; }; }, [api]);
  return <Layout title={report ? `${report.ownerNickname}님의 반기 리포트` : "공유 리포트"} lead="15분 동안 이 report revision만 메모리 viewer session으로 읽습니다." localOnly><ErrorBox error={error} />{!report && !error ? <p role="status">공유 리포트를 여는 중…</p> : report && <><dl className={styles.metrics}><div><dt>감상</dt><dd>{report.report.metrics.viewingCount}</dd></div><div><dt>평가</dt><dd>{report.report.metrics.ratedCount}</dd></div><div><dt>평균</dt><dd>{report.report.metrics.averageRating ?? "없음"}</dd></div></dl><ul className={styles.rows}>{report.report.periodItems.items.map((item) => <li key={`${item.movieId}-${item.watchedAt}`}><strong>{item.displayTitle}</strong></li>)}</ul><More enabled={report.report.periodItems.hasNext && Boolean(report.report.periodItems.nextCursor)} onClick={() => void load(report.report.periodItems.nextCursor ?? undefined)} /></>}</Layout>;
}

export function NotificationsPage() {
  const { api } = useC5(); const [settings, setSettings] = useState<Awaited<ReturnType<typeof api.getNotificationSettings>> | null>(null); const [page, setPage] = useState<NotificationPage | null>(null); const [error, setError] = useState<unknown>();
  async function load(cursor?: string) { try { const next = await api.listNotifications(cursor); setPage((current) => cursor && current ? { ...next, items: [...current.items, ...next.items] } : next); } catch (reason) { setError(reason); } }
  useEffect(() => { void Promise.all([api.getNotificationSettings(), api.listNotifications()]).then(([nextSettings, nextPage]) => { setSettings(nextSettings); setPage(nextPage); }).catch(setError); }, [api]);
  async function toggle() { if (!settings) return; try { setSettings(await api.replaceNotificationSettings(!settings.watchConfirmationDueEnabled, settings.revision)); } catch (reason) { setError(reason); } }
  async function update(item: InAppNotification, state: "READ" | "DISMISSED") { try { const next = await api.updateNotification(item.notificationId, state); setPage((current) => current ? { ...current, items: current.items.map((value) => value.notificationId === next.notificationId ? next : value) } : current); } catch (reason) { setError(reason); } }
  return <Layout title="앱 알림" lead="WATCH_CONFIRMATION_DUE만 앱 안에서 보여주며 외부 발송은 하지 않습니다."><ErrorBox error={error} />{settings && <label className={styles.toggle}><input type="checkbox" checked={settings.watchConfirmationDueEnabled} onChange={toggle} />감상 확인 알림 받기</label>}{!page ? <p role="status">알림을 불러오는 중…</p> : page.items.length === 0 ? <p className={styles.empty}>새 알림이 없어요.</p> : <ul className={styles.notifications}>{page.items.map((item) => <li key={item.notificationId}><div><strong>{item.state}</strong><p>{item.message}</p></div><div className={styles.actions}>{item.state === "UNREAD" && <button className={styles.secondary} onClick={() => update(item, "READ")}>읽음</button>}{item.state !== "DISMISSED" && <button className={styles.danger} onClick={() => update(item, "DISMISSED")}>숨기기</button>}</div></li>)}</ul>}<More enabled={Boolean(page?.hasNext && page.nextCursor)} onClick={() => void load(page?.nextCursor ?? undefined)} /></Layout>;
}
